name: Python Coninuous Integration
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      working-directory: train/extraction
      run: |
        python -m pip install --upgrade pip
        pip install --user pipenv
    - name: Format with Black
      run: |
        pipenv install
        pipenv run black train
        pipenv run black train --check
    - name: Lint with flake8
      run: |
        pipenv install
        pipenv run flake8 . --exit-zero
    - name: Run unit tests
      working-directory: train/extraction
      run: |
        pipenv install
        pipenv sync --dev
        #pipenv shell
        pipenv run coverage run -m unittest tests.extraction_test
        pipenv run coverage report