name: Python Continuous Integration
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11.1"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --user pipenv
    - name: Format with Black
      run: |
        pipenv install --dev
        pipenv run black train
        pipenv run black train --check
    - name: Lint with flake8
      run: |
        pipenv install --dev
        pipenv run flake8 .
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11.1"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --user pipenv
    - name: Build packages extraction
      run: |
         chmod +x ./bin/build_package.sh
         ./bin/build_package.sh packages/extraction train/extraction mlopspython_extraction mlopspython-extraction
    - name: Publish package extraction
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      continue-on-error: true
      with:
        packages_dir: packages/extraction/dist
        skip-existing: true
        verbose: true
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
    - name: Wait 30 seconds
      run: |
        sleep 30
    - name: Run unit tests Extraction
      working-directory: train/extraction
      run: |
        pipenv install --dev
        pipenv run coverage run -m unittest tests.extraction_test
        pipenv run coverage report
    - name: Run unit tests Label Split Data
      working-directory: train/label_split_data
      run: |
        pipenv install --dev
        pipenv run coverage run -m unittest tests.label_split_data_test
        pipenv run coverage report
    - name: Run unit tests Train
      working-directory: train/train
      run: |
        pipenv install --dev
        pipenv run python -m unittest tests.train_test
    - name: Build package inference
      run: |
        chmod +x ./bin/build_package.sh
        ./bin/build_package.sh packages/inference train/evaluate mlopspython_inference mlopspython-inference
    - name: Publish package inference
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      continue-on-error: true
      with:
        packages_dir: packages/inference/dist
        skip-existing: true
        verbose: true
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
    - name: Wait 30 seconds
      run: |
        sleep 30
    - name: Run unit tests Evaluate
      working-directory: train/evaluate
      run: |
        pipenv install --dev
        pipenv run python -m unittest tests.evaluate_test
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZUREML_CREDENTIALS}}
    - name: run train/azure/run_pipeline.py.py
      run: |
          pipenv install
          pipenv run python azureml_run_pipeline.py
      working-directory: train
    - name: download model
      run: |
          az extension add -n ml
          az ml model download --name cats-dogs-others --version 14 --resource-group azure-ml --workspace-name cats-dogs
      working-directory: production/api
